### ISSUE TITLE
Cite this

### ISSUE THREAD

**Issue by josemarialuna** [deric/clustering-benchmark#5]
Hi there,

we are going to use some of these datasets in the experiments of a paper. Is there any publication that we can cite?

**Comment by deric** [comment]
Hi, thanks for looking into this. The datasets were used in [Chameleon 2 paper](https://dl.acm.org/doi/abs/10.1145/3299876), but there's no special publications just for the datasets. Where it was possible, there are [annotations](https://github.com/deric/clustering-benchmark/blob/master/src/main/resources/datasets/artificial/aggregation.arff#L3) for the original source. 

The idea was to put diverse clustering problems used in literature into one place. Some generated datasets were saved in order to allow repeating experiments on new algorithms.

Some artificial datasets comes from the original [Chameleon paper](https://ieeexplore.ieee.org/abstract/document/781637) (in some cases we couldn't recover the original data).

See e.g. http://cs.joensuu.fi/sipu/datasets/ which contains nice collections of datasets with references.

**Comment by josemarialuna** [comment]
Thank you so much for your quick answer! We will have those comments into consideration for our experiments! 

Best!
